const products = [
  {
    id: 'ue5-mcp',
    icon: 'Gamepad2',
    price: 499.99,
    currency: 'EUR',
    tags: ['C++', 'Unreal Engine 5', 'MCP'],

    content: {
      en: {
        name: 'UE5 Editor MCP',
        subtitle: 'The Most Complete AI Bridge for the UE5 Editor',
        description: 'A native-C++ Model Context Protocol bridge exposing 604 tools (backed by ~700 reflected C++ functions across 21 editor libraries) that let any MCP-compatible AI drive the Unreal Engine 5 editor. ~150,000 lines of editor C++ plus a zero-dependency Node.js MCP server - native execution, not Python round-trips.',
        features: [
          '604 MCP tools across 21 editor libraries, auto-generated by UFUNCTION reflection',
          'Native C++ execution with race-safe game-thread marshaling (no Python wrapper)',
          'NodeForge: a pseudo-code to Blueprint node-graph compiler with auto-layout, validation, and undo',
          'Covers GAS, World Partition, PCG, Niagara, Sequencer, materials, rendering, Python, PIE, and screenshots',
        ],
      },
      fr: {
        name: 'UE5 Editor MCP',
        subtitle: 'Le Bridge IA le Plus Complet pour l\'Editeur UE5',
        description: 'Un bridge Model Context Protocol en C++ natif exposant 604 outils (adosses a ~700 fonctions C++ reflechies sur 21 bibliotheques editeur) permettant a toute IA compatible MCP de piloter l\'editeur Unreal Engine 5. ~150 000 lignes de C++ editeur plus un serveur MCP Node.js sans dependance - execution native, pas d\'aller-retours Python.',
        features: [
          '604 outils MCP sur 21 bibliotheques editeur, generes par reflexion UFUNCTION',
          'Execution C++ native avec marshaling thread-safe sur le game thread (sans wrapper Python)',
          'NodeForge : un compilateur pseudo-code vers graphe de noeuds Blueprint (auto-layout, validation, undo)',
          'Couvre GAS, World Partition, PCG, Niagara, Sequencer, materiaux, rendu, Python, PIE et captures',
        ],
      },
    },
  },
  {
    id: 'dynamic-quest-system',
    icon: 'Gamepad2',
    price: 599.99,
    currency: 'EUR',
    tags: ['C++', 'Unreal Engine 5', 'Gameplay'],

    content: {
      en: {
        name: 'Dynamic Quest System',
        subtitle: 'Production-Grade UE5 Quest Framework',
        description: '52,000+ lines of C++ delivering a complete quest framework for Unreal Engine 5. Modular condition/objective architecture, async operations, thread-safe design, binary serialization, and support for 100+ concurrent quests per player.',
        features: [
          'Modular condition and objective architecture',
          'Async operations with thread-safe design',
          'Binary serialization and visual editor',
          'Event-driven progression with Blueprint integration',
        ],
      },
      fr: {
        name: 'Dynamic Quest System',
        subtitle: 'Framework de Quetes UE5 Production',
        description: '52 000+ lignes de C++ pour un framework de quetes complet pour Unreal Engine 5. Architecture modulaire condition/objectif, operations asynchrones, design thread-safe, serialisation binaire et support 100+ quetes concurrentes par joueur.',
        features: [
          'Architecture modulaire condition/objectif',
          'Operations asynchrones et design thread-safe',
          'Serialisation binaire et editeur visuel',
          'Progression evenementielle avec integration Blueprint',
        ],
      },
    },
  },
  {
    id: 'rz-indirect-instancing',
    icon: 'Cpu',
    price: 699.99,
    currency: 'EUR',
    tags: ['C++', 'Unreal Engine 5', 'Rendering'],

    content: {
      en: {
        name: 'RzIndirectInstancing',
        subtitle: 'Custom GPU Instancing & Vertex Factory',
        description: '20,000+ lines of C++ implementing a custom vertex factory and GPU instancing system for UE5. RHI-level optimizations, custom HLSL/SM6 shaders, LOD support, and GPU scene mesh integration. Optimized for UE 5.7.',
        features: [
          'Custom vertex factory with RHI-level optimizations',
          'HLSL/SM6 shader development',
          'LOD support and GPU scene mesh integration',
          'Efficient rendering of high-count instances',
        ],
      },
      fr: {
        name: 'RzIndirectInstancing',
        subtitle: 'Instanciation GPU & Vertex Factory Custom',
        description: '20 000+ lignes de C++ implementant un vertex factory custom et un systeme d\'instanciation GPU pour UE5. Optimisations RHI, shaders HLSL/SM6 custom, support LOD et integration GPU scene mesh. Optimise pour UE 5.7.',
        features: [
          'Vertex factory custom avec optimisations RHI',
          'Developpement de shaders HLSL/SM6',
          'Support LOD et integration GPU scene mesh',
          'Rendu efficace de grandes quantites d\'instances',
        ],
      },
    },
  },
  {
    id: 'backblaze-mcp',
    icon: 'HardDrive',
    price: 249.99,
    currency: 'EUR',
    tags: ['TypeScript', 'MCP', 'Backup'],

    content: {
      en: {
        name: 'Backblaze Computer Backup MCP',
        subtitle: 'AI Backup Management - Reverse Engineered',
        description: 'MCP server for Backblaze Computer Backup (not B2). Built through extensive reverse engineering of Backblaze\'s proprietary protocol - no public API exists for this. Browse, search, and restore files through AI.',
        features: [
          'Full file browsing and search across backups',
          'Restore creation and status monitoring',
          'Multi-computer support with 2FA',
          'Reverse-engineered protocol - the only MCP for non-B2 Backblaze',
        ],
      },
      fr: {
        name: 'Backblaze Computer Backup MCP',
        subtitle: 'Gestion de Backup IA - Reverse Engineere',
        description: 'Serveur MCP pour Backblaze Computer Backup (pas B2). Construit par reverse engineering approfondi du protocole proprietaire Backblaze - aucune API publique n\'existe. Parcourez, recherchez et restaurez des fichiers via IA.',
        features: [
          'Navigation et recherche completes dans les backups',
          'Creation de restaurations et suivi de statut',
          'Support multi-ordinateur avec 2FA',
          'Protocole reverse-engineere - le seul MCP pour Backblaze non-B2',
        ],
      },
    },
  },
  {
    id: 'rzcloak',
    icon: 'Shield',
    price: 249.99,
    currency: 'EUR',
    tags: ['Rust', 'Security', 'Windows'],

    content: {
      en: {
        name: 'RzCloak',
        subtitle: 'Binary Protection Tool',
        description: 'Rust-based binary protection and obfuscation tool for Windows executables. Hardens your compiled binaries against reverse engineering and tampering.',
        features: [
          'PE binary obfuscation and hardening',
          'Anti-debugging and anti-tampering checks',
          'Import table protection',
          'Lightweight - no runtime dependencies',
        ],
      },
      fr: {
        name: 'RzCloak',
        subtitle: 'Outil de Protection Binaire',
        description: 'Outil de protection et d\'obfuscation de binaires en Rust pour les executables Windows. Renforce vos binaires compiles contre le reverse engineering et la falsification.',
        features: [
          'Obfuscation et renforcement de binaires PE',
          'Protections anti-debugging et anti-tampering',
          'Protection de la table d\'imports',
          'Leger - aucune dependance runtime',
        ],
      },
    },
  },
  {
    id: 'trace-exporter',
    icon: 'Cpu',
    price: 99.99,
    currency: 'EUR',
    tags: ['Rust', 'Unreal Engine 5', 'Profiling'],

    content: {
      en: {
        name: 'TraceFrameExporter',
        subtitle: 'Unreal Insights Trace Analyzer',
        description: 'AI-friendly Unreal Insights trace analyzer. Extracts structured performance data from .utrace files - frame stats, CPU/GPU timers, thread breakdowns - into formats AI tools can reason about.',
        features: [
          'Aggregated frame analysis (avg/p95/p99)',
          'Hierarchical call trees with timing data',
          'Thread breakdown with percentage attribution',
          'CLI tool - integrates into any pipeline',
        ],
      },
      fr: {
        name: 'TraceFrameExporter',
        subtitle: 'Analyseur de Traces Unreal Insights',
        description: 'Analyseur de traces Unreal Insights optimise pour l\'IA. Extrait des donnees de performance structurees depuis les fichiers .utrace - stats de frames, timers CPU/GPU, ventilation par thread.',
        features: [
          'Analyse agregee de frames (avg/p95/p99)',
          'Arbres d\'appels hierarchiques avec donnees de timing',
          'Ventilation par thread avec attribution en pourcentage',
          'Outil CLI - s\'integre dans tout pipeline',
        ],
      },
    },
  },
  {
    id: 'server-manager-template',
    icon: 'Gamepad2',
    price: 99.99,
    currency: 'EUR',
    tags: ['Rust', 'SSH', 'egui'],

    content: {
      en: {
        name: 'Game Server Manager',
        subtitle: 'Rust SSH Server Management GUI',
        description: 'Template Rust/egui application for managing dedicated game servers via SSH. Multi-region support, real-time log streaming, and secure credential storage. Adapt it to any game server.',
        features: [
          'Multi-region server management',
          'Real-time log streaming and monitoring',
          'Encrypted SSH key storage',
          'Audio alerts for server events',
        ],
      },
      fr: {
        name: 'Game Server Manager',
        subtitle: 'GUI Rust de Gestion Serveur SSH',
        description: 'Application template Rust/egui pour gerer des serveurs de jeu dedies via SSH. Support multi-region, streaming de logs en temps reel et stockage securise. Adaptable a tout serveur de jeu.',
        features: [
          'Gestion de serveurs multi-regions',
          'Streaming et monitoring de logs en temps reel',
          'Stockage chiffre de cles SSH',
          'Alertes audio pour les evenements serveur',
        ],
      },
    },
  },
  {
    id: 'custom-dev',
    icon: 'Cpu',
    price: null,
    currency: 'EUR',
    tags: ['C++', 'Rust', 'MCP'],
    isService: true,

    content: {
      en: {
        name: 'Custom Development',
        subtitle: 'Tools & Plugins On Demand',
        description: 'Need a custom MCP server, UE5 plugin, Rust tool, or automation solution? I build production-grade software tailored to your exact requirements.',
        features: [
          'Custom MCP servers for any service',
          'UE5 C++ plugin development',
          'Rust CLI tools and GUI applications',
          'Reverse engineering and systems integration',
        ],
      },
      fr: {
        name: 'Developpement Sur Mesure',
        subtitle: 'Outils & Plugins a la Demande',
        description: 'Besoin d\'un serveur MCP custom, d\'un plugin UE5, d\'un outil Rust ou d\'une solution d\'automatisation ? Je developpe des logiciels de qualite production adaptes a vos besoins.',
        features: [
          'Serveurs MCP custom pour tout service',
          'Developpement de plugins C++ UE5',
          'Outils CLI et applications GUI en Rust',
          'Reverse engineering et integration systeme',
        ],
      },
    },
  },
];

export default products;
